.frontend-test:
  image: node:12
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - frontend/**/*
  before_script:
    - cd frontend

cache:
  paths:
    - frontend/node_modules/

install:
  extends: .frontend-test
  stage: .pre
  script:
    - yarn

lint:
  extends: .frontend-test
  stage: test
  script:
    - yarn
    - yarn lint
    - yarn test
  needs: [install]

test:
  extends: .frontend-test
  stage: test
  script:
    - yarn
    - yarn test
  needs: [install]

build:
  extends: .frontend-test
  stage: build
  script:
    - yarn
    - yarn build
  needs: [install]
