image: maven:3.6.3-slim

stages:
  - package

default:
  before_script:
    - cd backend

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

cache:
  paths:
    - .m2/repository

package:
  stage: test
  script: mvn package 
  artifacts:
    paths:
      - .m2/repository

