image: maven:3.6.3-slim

stages:
  - package

default:
  before_script:
    - cd backend

cache:
  paths:
    - .m2/repository

package:
  stage: package
  script: mvn package --activate-profiles test
  artifacts:
    paths:
      - .m2/repository

